### ISSUE TITLE
Peer to Peer Code Review

### ISSUE THREAD

**Issue by marvin-nyalik** [abdozayan12/To-Do-List#6]

**Comment by marvin-nyalik** [comment]
Hey @abdozayan12. Great job implementing the project as per the requirements.
Great Highlights:

- Compact and easily readable codebase 👌
- Proper use of git flow and branches 🤞
- All requirements implemented and working perfectly ✔

Keep up the good job, Happy Coding.

**Comment by manzitresor** [comment]
Great job @abdozayan12 on implementing Project requirements. you have done great job 🦾 
### highlights🎯
✅ No Linter Error
✅ Well implemented Githubwork flow
✅ Decsriptive readme file
✅ user interactive

    however I would suggest you the following changes to make your project look more professional

- [ ] In your read me file try to create your own MIT LICENSE. This will help your read your read me more professional

 "Other than that, you have done a great job! Keep up the good work! 🍾"
